---
- name: local.yml
  become: true
  hosts: all
  gather_facts: true

  tasks:
  - name: Grab the Vendor from dmidecode
    ansible.builtin.shell: 'dmidecode | grep Vendor'
    register: vendor
    ignore_errors: true

  - name: Just print the value of vendor
    ansible.builtin.debug:
      msg: {{ vendor.stdout }}
      
  - name: Install qemu-guest-agent if its a Proxmox VM and distribution is Ubuntu
    ansible.builtin.apt:
      name: qemu-guest-agent
      state: present
    when: vendor.stdout.find('Proxmox') != -1 and ansible_facts['distribution'] == "Debian"
