---
- name: local.yml
  become: true
  hosts: all
  gather_facts: true

  tasks:
  - name: Gather the package facts
    ansible.builtin.package_facts:
      manager: auto

  - name: Call the grype role if grype is not already installed
    include_role:
      name: grype
    when: "'grype' not in ansible_facts.packages"

  - name: Just print the ansible_system_vendor
    debug:
      msg: "{{ ansible_system_vendor }}"
      
  - name: Call the qemu-guest-agent role if its a Proxmox VM
    include_role:
      name: qemu-guest-agent
    when: ansible_system_vendor == "QEMU"

  - name: Call the syft role if syft is not already installed
    include_role:
      name: syft
    when: "'syft' not in ansible_facts.packages"
