---
- name: local.yml
  become: true
  hosts: all
  gather_facts: true

  tasks:
  - name: Grab the Vendor from dmidecode
    ansible.builtin.shell: 'dmidecode | grep Vendor'
    register: vendor
    ignore_errors: true

  - name: Gather the package facts
    ansible.builtin.package_facts:
      manager: auto

  - name: Call the grype role if grype is not already installed
    include_role:
      name: grype
    when: "'grype' not in ansible_facts.packages"

  - name: Call the qemu-guest-agent role if its a Proxmox VM
    include_role:
      name: qemu-guest-agent
    when: vendor.stdout.find('Proxmox') != -1

  - name: Call the syft role if syft is not already installed
    include_role:
      name: syft
    when: "'syft' not in ansible_facts.packages"
