---
# tasks file for grype
  - name: Download and the Grype .deb package if its a Debian based distribution
    ansible.builtin.get_url:
      url: https://github.com/anchore/grype/releases/download/v0.84.0/grype_0.84.0_linux_amd64.deb
      dest: /tmp/grype_0.84.0_linux_amd64.deb
    when: ansible_facts['os_family'] == "Debian"

  - name: Download and the Grype .deb package if its a RedHat based distribution
    ansible.builtin.get_url:
      url: https://github.com/anchore/grype/releases/download/v0.84.0/grype_0.84.0_linux_amd64.rpm
      dest: /tmp/grype_0.84.0_linux_amd64.rpm
    when: ansible_facts['os_family'] == "RedHat"