---
# tasks file for grype
  - name: Download and the Grype .deb package if its a Debian based distribution
    ansible.builtin.get_url:
      url: "https://github.com/anchore/grype/releases/download/v{{ version }}/grype_{{ version }}_linux_amd64.deb"
      dest: "/tmp/grype_{{ version }}_linux_amd64.deb"
    when: ansible_facts['os_family'] == "Debian"

  - name: Download and the Grype .rpm package if its a RedHat based distribution
    ansible.builtin.get_url:
      url: "https://github.com/anchore/grype/releases/download/v{{ version }}/grype_{{ version }}_linux_amd64.rpm"
      dest: "/tmp/grype_{{ version }}_linux_amd64.rpm"
    when: 
      - ansible_facts['os_family'] == "RedHat"
      - ansible_facts['distribution'] != "Fedora"

  - name: Install grype when OS Family is Debian
    ansible.builtin.apt:
      deb: "/tmp/grype_{{ version }}_linux_amd64.deb"
      state: present
    when: ansible_facts['os_family'] == "Debian"

  - name: Install grype when OS Family is RedHat
    ansible.builtin.dnf:
      name: "/tmp/grype_{{ version }}_linux_amd64.rpm"
      state: present
    when: 
      - ansible_facts['os_family'] == "RedHat"
      - ansible_facts['distribution'] != "Fedora"