---
# tasks file for syft
  - name: Download and the Syft .deb package if its a Debian based distribution
    ansible.builtin.get_url:
      url: "https://github.com/anchore/syft/releases/download/v{{ version }}/syft_{{ version }}_linux_amd64.deb"
      dest: "/tmp/syft_{{ version }}_linux_amd64.deb"
    when: ansible_facts['os_family'] == "Debian"

  - name: Download and the Syft .rpm package if its a RedHat based distribution
    ansible.builtin.get_url:
      url: "https://github.com/anchore/syft/releases/download/v{{ version }}/syft_{{ version }}_linux_amd64.rpm"
      dest: "/tmp/syft_{{ version }}_linux_amd64.rpm"
    when: ansible_facts['os_family'] == "RedHat"

  - name: Install syft when OS Family is Debian
    ansible.builtin.apt:
      deb: "/tmp/syft_{{ version }}_linux_amd64.deb"
      state: present
    when: ansible_facts['os_family'] == "Debian"

  - name: Install syft when OS Family is RedHat
    ansible.builtin.dnf:
      name: "/tmp/syft_{{ version }}_linux_amd64.rpm"
      state: present
    when: ansible_facts['os_family'] == "RedHat"