---
# tasks file for grafana-agent-flow
  - name: Download and the Grafan Agent Flow .deb package if its a Debian based distribution
    ansible.builtin.get_url:
      url: "https://github.com/grafana/agent/releases/download/v{{ version }}/grafana-agent-flow-{{ version }}-1.amd64.deb"
      dest: "/tmp/grafana-agent-flow-{{ version }}-1.amd64.deb"
    when: ansible_facts['os_family'] == "Debian"

  - name: Download and the Grafan Agent Flow .rpm package if its a RedHat based distribution, but not Fedora
    ansible.builtin.get_url:
      url: "https://github.com/grafana/agent/releases/download/v{{ version }}/grafana-agent-flow-{{ version }}-1.amd64.rpm"
      dest: "/tmp/grafana-agent-flow-{{ version }}-1.amd64.rpm"
    when: ansible_facts['os_family'] == "RedHat"

  - name: Install Grafan Agent Flow when OS Family is Debian
    ansible.builtin.apt:
      deb: "/tmp/grafana-agent-flow-{{ version }}-1.amd64.deb"
      state: present
    when: ansible_facts['os_family'] == "Debian"

  - name: Install Grafan Agent Flow when OS Family is RedHat
    ansible.builtin.dnf:
      name: "/tmp/grafana-agent-flow-{{ version }}-1.amd64.rpm"
      state: present
    when: ansible_facts['os_family'] == "RedHat"

  - name: Install Grafana Agent Flow Config File
    ansible.builtin.template:
      src: grafana-agent-flow.river.j2
      dest: /etc/grafana-agent-flow.river
      owner: grafana-agent-flow
      group: grafana-agent
      mode: '0640'

  - name: Adjust /etc/default/grafana-agent-flow to listen on 0.0.0.0
    ansible.builtin.lineinfile:
      path: /etc/default/grafana-agent-flow
      regexp: '^CUSTOM_ARGS='
      line: 'CUSTOM_ARGS="--server.http.listen-addr=0.0.0.0:12345"'

  - name: Restart Grafana Agent Flow Service
    ansible.builtin.service:
      name: grafana-agent-flow
      state: restarted
      enabled: true
